### ISSUE TITLE
win10系统报错

### ISSUE THREAD

**Issue by kohyzsc123** [smityliu/xuexiqiangguo-automation-#1]
* 环境：win10

```
D:\Personal\Desktop\xuexiqiangguo-automation--master\windows>python windows_exp.py
windows_exp.py:100: DeprecationWarning: use options instead of chrome_options
  driver= webdriver.Chrome('./chromedriver.exe',chrome_options=chrome_options)
Traceback (most recent call last):
  File "windows_exp.py", line 100, in <module>
    driver= webdriver.Chrome('./chromedriver.exe',chrome_options=chrome_options)
  File "D:\anaconda3\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "D:\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "D:\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
```

**Comment by smityliu** [comment]
我也是win10，你是不是没有把chromedriver.exe放在python脚本同目录下

**Comment by smityliu** [comment]
> * 环境：win10
> 
> ```
> D:\Personal\Desktop\xuexiqiangguo-automation--master\windows>python windows_exp.py
> windows_exp.py:100: DeprecationWarning: use options instead of chrome_options
>   driver= webdriver.Chrome('./chromedriver.exe',chrome_options=chrome_options)
> Traceback (most recent call last):
>   File "windows_exp.py", line 100, in <module>
>     driver= webdriver.Chrome('./chromedriver.exe',chrome_options=chrome_options)
>   File "D:\anaconda3\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
>     desired_capabilities=desired_capabilities)
>   File "D:\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
>     self.start_session(capabilities, browser_profile)
>   File "D:\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
>     response = self.execute(Command.NEW_SESSION, parameters)
>   File "D:\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "D:\anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
> ```

我知道你的问题了，你的问题是因为这个相对路径('./chromedriver.exe',）在win10下面没有办法识别，如果你是把chromedriver和python脚本放在桌面是没办法在cmd跑起来的，两种办法，

你把./chromedriver改成绝对路径，或者，

你可以把脚本和chromedriver拖到一个文件夹里，然后用powershell来运行

**Comment by kohyzsc123** [comment]
> 
> 
> > * 环境：win10
> > 
> > ```
> > D:\Personal\Desktop\xuexiqiangguo-automation--master\windows>python windows_exp.py
> > windows_exp.py:100: DeprecationWarning: use options instead of chrome_options
> >   driver= webdriver.Chrome('./chromedriver.exe',chrome_options=chrome_options)
> > Traceback (most recent call last):
> >   File "windows_exp.py", line 100, in <module>
> >     driver= webdriver.Chrome('./chromedriver.exe',chrome_options=chrome_options)
> >   File "D:\anaconda3\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
> >     desired_capabilities=desired_capabilities)
> >   File "D:\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
> >     self.start_session(capabilities, browser_profile)
> >   File "D:\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
> >     response = self.execute(Command.NEW_SESSION, parameters)
> >   File "D:\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
> >     self.error_handler.check_response(response)
> >   File "D:\anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
> >     raise exception_class(message, screen, stacktrace)
> > selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
> > ```
> 
> 我知道你的问题了，你的问题是因为这个相对路径('./chromedriver.exe',）在win10下面没有办法识别，如果你是把chromedriver和python脚本放在桌面是没办法在cmd跑起来的，两种办法，
> 
> 你把./chromedriver改成绝对路径，或者，
> 
> 你可以把脚本和chromedriver拖到一个文件夹里，然后用powershell来运行

谢谢回复，这两种方式我都试过了，不过依然报错，报错信息与之前一致

**Comment by smityliu** [comment]
能留个联系方式吗，我看看什么问题



---原始邮件---
发件人: "kohyzsc123"<notifications@github.com&gt;
发送时间: 2020年2月20日(周四) 中午1:54
收件人: "smityliu/xuexiqiangguo-automation-"<xuexiqiangguo-automation-@noreply.github.com&gt;;
抄送: "Manual"<manual@noreply.github.com&gt;;"smityliu"<790236835@qq.com&gt;;
主题: Re: [smityliu/xuexiqiangguo-automation-] win10系统报错 (#1)


   
环境：win10 
 D:\Personal\Desktop\xuexiqiangguo-automation--master\windows&gt;python windows_exp.py windows_exp.py:100: DeprecationWarning: use options instead of chrome_options   driver= webdriver.Chrome('./chromedriver.exe',chrome_options=chrome_options) Traceback (most recent call last):   File "windows_exp.py", line 100, in <module&gt;     driver= webdriver.Chrome('./chromedriver.exe',chrome_options=chrome_options)   File "D:\anaconda3\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__     desired_capabilities=desired_capabilities)   File "D:\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__     self.start_session(capabilities, browser_profile)   File "D:\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session     response = self.execute(Command.NEW_SESSION, parameters)   File "D:\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute     self.error_handler.check_response(response)   File "D:\anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response     raise exception_class(message, screen, stacktrace) selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary   
我知道你的问题了，你的问题是因为这个相对路径('./chromedriver.exe',）在win10下面没有办法识别，如果你是把chromedriver和python脚本放在桌面是没办法在cmd跑起来的，两种办法，
 
你把./chromedriver改成绝对路径，或者，
 
你可以把脚本和chromedriver拖到一个文件夹里，然后用powershell来运行
  
谢谢回复，这两种方式我都试过了，不过依然报错，报错信息与之前一致

**Comment by smityliu** [comment]
> > > * 环境：win10
> > > 
> > > ```
> > > D:\Personal\Desktop\xuexiqiangguo-automation--master\windows>python windows_exp.py
> > > windows_exp.py:100: DeprecationWarning: use options instead of chrome_options
> > >   driver= webdriver.Chrome('./chromedriver.exe',chrome_options=chrome_options)
> > > Traceback (most recent call last):
> > >   File "windows_exp.py", line 100, in <module>
> > >     driver= webdriver.Chrome('./chromedriver.exe',chrome_options=chrome_options)
> > >   File "D:\anaconda3\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
> > >     desired_capabilities=desired_capabilities)
> > >   File "D:\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
> > >     self.start_session(capabilities, browser_profile)
> > >   File "D:\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
> > >     response = self.execute(Command.NEW_SESSION, parameters)
> > >   File "D:\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
> > >     self.error_handler.check_response(response)
> > >   File "D:\anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
> > >     raise exception_class(message, screen, stacktrace)
> > > selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
> > > ```
> > 
> > 
> > 我知道你的问题了，你的问题是因为这个相对路径('./chromedriver.exe',）在win10下面没有办法识别，如果你是把chromedriver和python脚本放在桌面是没办法在cmd跑起来的，两种办法，
> > 你把./chromedriver改成绝对路径，或者，
> > 你可以把脚本和chromedriver拖到一个文件夹里，然后用powershell来运行
> 
> 谢谢回复，这两种方式我都试过了，不过依然报错，报错信息与之前一致

可能是你没有装chrome浏览器，我后来查了一下，是要下载一个chrome浏览器的，chromedriver只是调用了浏览器的驱动而已，您下一个最新版的chrome浏览器默认安装就可以了
